### ISSUE TITLE
PyPi/Versioning

### ISSUE THREAD

**Issue by wudstrand** [florimondmanca/httpx-sse#1]
Can you version this library, or add aa beta tag to the repository so I can addd this as a dependency without risk of it breaking when you develop?

Questions about the libraries timeline.
- When will this library be published to PyPI? 
- When will you start versioning the project?

**Comment by Kludex** [comment]
You can use the commit as a pin. :eyes:

**Comment by florimondmanca** [comment]
It's up, now! https://pypi.org/project/httpx-sse/0.1.0
