### ISSUE TITLE
Support requests made with any HTTP method, such as POST

### ISSUE THREAD

**Issue by zeitderforschung** [florimondmanca/httpx-sse#3]
Background: The popular OpenAI API supports server-sent events, but uses POST requests, see https://platform.openai.com/docs/api-reference/completions. It is not possible to change the request type as it is hard-coded: https://github.com/florimondmanca/httpx-sse/blob/61826350c0d236673b2f95b0165cb533121fc018/src/httpx_sse/_api.py#L50.

**Comment by florimondmanca** [comment]
Hi @zeitderforschung 

Oh well, I hadn't thought SSE could be requested over methods other than GET, but since it's a merely a response format, that makes sense.

Do we know from a spec if _any_ HTTP method is accepted, or is there a specific set of HTTP methods that are allowed for SSE endpoints?

**Comment by zeitderforschung** [comment]
Hi @florimondmanca, 

thank you for the fast response. There is a post on StackOverflow: https://stackoverflow.com/questions/34261928/can-server-sent-events-sse-with-eventsource-pass-parameter-by-post:

> The [standard](http://www.w3.org/TR/eventsource/) doesn't explicitly say POST cannot be used. But, unlike XMLHttpRequest, there is no parameter to specify the http method to use, and no way to specify the data you want to post.

The method parameter would fit perfectly and I believe other SSE clients do it the same way, for example aiohttp-sse-client. https://github.com/rtfol/aiohttp-sse-client/blob/e311075ac8b9b75d8b09512f8638f1dd03e2ef2b/aiohttp_sse_client/client.py#L114

**Comment by florimondmanca** [comment]
Right, this tends to confirm this new form `connect(client, method, url, **kwargs)`. The goal here would also be to match `Client.request(method, url, **kwargs)` from HTTPX itself, so it's nice and consistent.

**Comment by r4fek** [comment]
Can we merge it please?
