### ISSUE TITLE
update headers (token) on the fly

### ISSUE THREAD

**Issue by Reapor-Yurnero** [florimondmanca/httpx-sse#6]
Many authorization tokens expire after a certain period e.g. 1hr. To maintain the stream, the token needs to be updated. Is there anyway to do this on the fly with this package? Thank you!

**Comment by florimondmanca** [comment]
@Reapor-Yurnero This sounds like something you'd address at the HTTPX level, using [Custom authentication flow](https://www.python-httpx.org/advanced/#customizing-authentication). You can see an example of token renewal handling at the end of that docs section.

Cheers!
